
import React from 'react';
import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';
import { StockItem } from '@/types';

const styles = StyleSheet.create({
    page: {
        padding: 10,
        fontFamily: 'Helvetica',
        backgroundColor: '#ffffff',
    },
    labelContainer: {
        width: '100%',
        height: '100%',
        borderWidth: 0,
        padding: 5,
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    brand: {
        fontSize: 6,
        fontWeight: 'bold',
        color: '#64748b',
        textTransform: 'uppercase',
        marginBottom: 2,
    },
    productName: {
        fontSize: 8,
        fontWeight: 'extrabold',
        color: '#0f172a',
        textAlign: 'center',
        marginBottom: 4,
        maxLines: 2,
    },
    barcodeImage: {
        width: 120,
        height: 40,
        marginBottom: 2,
    },
    barcodeText: {
        fontSize: 7,
        fontFamily: 'Courier',
        color: '#1e293b',
        marginBottom: 4,
    },
    priceLabel: {
        fontSize: 10,
        fontWeight: 'black',
        color: '#0ea5e9',
    }
});

interface Props {
    product: StockItem;
    barcodeDataUrl: string; // The image generated by react-barcode
}

export const BarcodeLabelPDF: React.FC<Props> = ({ product, barcodeDataUrl }) => {
    return (
        <Document>
            {/* Small label format: 50mm x 30mm (approx 141pt x 85pt) */}
            <Page size={[141, 85]} style={styles.page}>
                <View style={styles.labelContainer}>
                    <Text style={styles.brand}>{product.brand || 'ENEA TELECOM'}</Text>
                    <Text style={styles.productName}>{product.name}</Text>

                    {barcodeDataUrl && (
                        <Image src={barcodeDataUrl} style={styles.barcodeImage} />
                    )}

                    <Text style={styles.barcodeText}>{product.barcode || product.ref}</Text>

                    {product.sellingPrice && (
                        <Text style={styles.priceLabel}>{product.sellingPrice.toLocaleString()} CFA</Text>
                    )}
                </View>
            </Page>
        </Document>
    );
};
